
#address to listen for broadcasts at
address: "tcp://localhost:6001"

# list of parameters to listen for, if empty, will listen for all broadcasts
params: ["dummy_instrument_random_number.param0","dummy_instrument_random_number.param2"]

# path to write data to for the CSV listener
csv_path: C:\Users\jmnol\OneDrive\Documents\InstrumentServerData\data.csv

# type of listener (where the listener writes data to)
type: "Influx"

# InfluxDB token for Influx listener
token: "token"

# InfluxDB org for Influx listener
org: "pfafflab"

# InfluxDB bucket for Influx listener
bucket: "testing"

# InfluxDB url for Influx listener
url: "http://localhost:8086"

# measurement Name for Influx listener
measurementName: "measurement"