
# addresses to listen for broadcasts at
addresses: ["tcp://128.174.164.60:6000","tcp://10.192.182.159:6000"]

# list of parameters to listen for, if empty, will listen for all broadcasts
params: []

# path to write data to for the CSV listener
csv_path: C:\Users\jmnol\OneDrive\Documents\InstrumentServerData\data.csv

# type of listener (where the listener writes data to)
type: "Influx"

# InfluxDB token for Influx listener
token: "pretty_fridges"

# InfluxDB org for Influx listener
org: "pfafflab"

# InfluxDB buckets for Influx listener, keyed by instrument name
bucketDict: {"fridge_nh": "niflheim","fridge_kk": "kelvin_klein"}

# InfluxDB url for Influx listener
url: "http://localhost:8086"

# measurement Name for Influx listener, keyed by instrument name
measurementNameDict: {"fridge_nh": "niflheim_telemetry", "fridge_kk": "kelvin_klein_telemetry"}